In [1]:
# importing libraries

import numpy as np
import pandas as pd
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
# reading csv file
df = pd.read_csv('preprocessed_housePrice.csv', header=0)
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [3]:
# importing Linear Regression
from sklearn.linear_model import LogisticRegression

In [4]:
lm = LogisticRegression()

In [5]:
# importing Test Train Split in Dataset
from sklearn.model_selection import train_test_split

In [6]:
# Independent Variables
x = df.loc[:, df.columns!='Sold']

In [7]:
x.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347    4.0875            1   
1       7.332     12.17280        42  0.046146    4.9675            0   
2       7.394     46.19856        38  0.045764    4.9675            0   
3       9.268     11.26720        45  0.047151    6.0650            1   
4       8.824     11.28960        55  0.039474    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [8]:
# Dependent variable
y = df['Sold']

In [9]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1)


In [11]:
print("x_train ", x_train.shape)

x_train  (404, 16)


In [12]:
print("x_test ", x_test.shape)

x_test  (102, 16)


In [13]:
print("y_train shape ", y_train.shape)

y_train shape  (404,)


In [14]:
print("y_test shape ", y_test.shape)

y_test shape  (102,)


In [15]:
# fitting the model to data
lm.fit(x_train, y_train)

LogisticRegression()

In [16]:
# prediction of dependent variable
y_test_pred = lm.predict(x_test)

In [17]:
print('y_test_pred', y_test_pred)

y_test_pred [1 1 0 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1
 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 1
 0 0 0 1 1 0 0 1 1 1 0 1 1 1 0 0 1 0 0 0 1 1 1 1 0 0 1 1]


In [18]:
# accuracy and confusion matrix
from sklearn.metrics import accuracy_score, confusion_matrix

In [19]:
confusion_matrix(y_test, y_test_pred)

array([[35, 14],
       [18, 35]], dtype=int64)

In [20]:
accuracy_score(y_test, y_test_pred)

0.6862745098039216

### K-Nearest Neighbors

In [21]:
from sklearn import preprocessing

# standardizing our x_train data
scaler = preprocessing.StandardScaler().fit(x_train)
x_train_s = scaler.transform(x_train)

In [24]:
print("x_train_s: ", x_train_s)

x_train_s:  [[ 0.31026354 -0.60928978 -0.89958293 ... -0.48525664 -0.3927922
   1.3151919 ]
 [ 0.08726679 -0.86952633 -0.85675635 ... -0.48525664 -0.3927922
  -0.76034532]
 [-1.70785697  1.02669166  1.25887674 ... -0.48525664  2.54587539
  -0.76034532]
 ...
 [-1.11691561  1.02669166  1.19891952 ... -0.48525664 -0.3927922
   1.3151919 ]
 [ 0.16531565 -0.713092   -0.39422928 ... -0.48525664 -0.3927922
  -0.76034532]
 [-0.16917946 -0.74818007 -0.4627518  ... -0.48525664 -0.3927922
   1.3151919 ]]


In [22]:
# standardizing our x_test data
scaler = preprocessing.StandardScaler().fit(x_test)
x_test_s = scaler.transform(x_test)

In [25]:
print("x_test_s", x_test_s)

x_test_s [[ 0.56587657 -1.33166171 -0.80076876 ... -0.4938648   2.23606798
  -0.72276418]
 [ 0.13333306 -1.09985593 -0.69316856 ... -0.4938648   2.23606798
  -0.72276418]
 [-0.60098498 -0.64638587 -1.01596915 ... -0.4938648  -0.4472136
   1.38357714]
 ...
 [-0.08796826 -0.40733616 -0.37036797 ... -0.4938648  -0.4472136
  -0.72276418]
 [-1.24477066  0.9748058   0.20349975 ... -0.4938648  -0.4472136
  -0.72276418]
 [-0.72169479  0.9748058   1.60230232 ... -0.4938648  -0.4472136
   1.38357714]]


In [26]:
from sklearn.neighbors import KNeighborsClassifier

# n_neighbors = Number of Neighbors
# running for k = 1
# creating object and fitting model
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train_s, y_train)

KNeighborsClassifier(n_neighbors=1)

In [27]:
confusion_matrix(y_test, knn.predict(x_test_s))

array([[30, 19],
       [26, 27]], dtype=int64)

In [29]:
accuracy_score(y_test, knn.predict(x_test_s))

0.5588235294117647

In [30]:
# running for k = 3
knn_3 = KNeighborsClassifier(n_neighbors=3)
knn_3.fit(x_train_s, y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
confusion_matrix(y_test, knn_3.predict(x_test_s))

array([[29, 20],
       [23, 30]], dtype=int64)

In [32]:
accuracy_score(y_test, knn_3.predict(x_test_s))

0.5784313725490197

**creating single model for multiple values of k using GridSearchCV**

In [33]:
from sklearn.model_selection import GridSearchCV 

In [34]:
params = {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}

In [36]:
# creating object
knn_grid = GridSearchCV(KNeighborsClassifier(), params)

In [37]:
knn_grid.fit(x_train_s, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [40]:
# finding out best parameter
knn_grid.best_params_

{'n_neighbors': 1}

In [39]:
# finding out best estimator
optimised_knn = knn_grid.best_estimator_

In [42]:
y_test_pred = optimised_knn.predict(x_test_s)
y_test_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [43]:
confusion_matrix(y_test, y_test_pred)

array([[30, 19],
       [26, 27]], dtype=int64)

In [44]:
accuracy_score(y_test, y_test_pred)

0.5588235294117647