In [1]:
### Importing Libraries

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
### Reading Dataset

df = pd.read_csv("Movie_regression.csv", header = 0)

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [4]:
df.shape

(506, 18)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Missing Value Imputation

- variable = Time_taken

In [6]:
df['Time_taken'].fillna(value =  df['Time_taken'].mean(), inplace = True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Dummy Variable Creation

- variable = 3D_available, Genre

In [8]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [9]:
df = pd.get_dummies(df, columns = ['3D_available', 'Genre'], drop_first=True)

In [10]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

In [11]:
df.shape

(506, 20)

### Splitting the Data

In [12]:
X = df.loc[:, df.columns!="Collection"]
type(X)

pandas.core.frame.DataFrame

In [13]:
X.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  3D_available_YES  Genre_Comedy  Genre_Drama  \
0              23            494                 1             0            0   
1              42            462                 0             0            1   
2              38            458                 0             1            0   
3              45            472                 1             0            1   
4              55            395                 0             0            1   

   Genre_Thriller  
0               1  
1               0  
2               0  
3               0  
4               0

In [14]:
X.shape

(506, 19)

In [15]:
y = df['Collection']
y.head()

0    48000
1    43200
2    69400
3    66800
4    72400
Name: Collection, dtype: int64

In [16]:
type(y)

pandas.core.series.Series

In [17]:
y.shape

(506,)

### Train Test Split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [23]:
print("Shape of X_train", X_train.shape)
print("Shape of X_test", X_test.shape)
print("Shape of y_train", y_train.shape)
print("Shape of y_train", y_train.shape)

Shape of X_train (404, 19)
Shape of X_test (102, 19)
Shape of y_train (404,)
Shape of y_train (404,)


### Standardizing the Data

In [25]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc = StandardScaler().fit(X_train)

In [28]:
X_train_STD = sc.transform(X_train)

In [29]:
X_test_STD = sc.transform(X_test)

In [30]:
X_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
220         162.0               8.485                8.640            8.485   
71           91.0               7.280                7.400            7.290   
240         127.8               6.755                6.935            6.800   
6           140.1               7.065                7.265            7.150   
417         162.6               9.135                9.305            9.095   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
220            8.670           8.52         480270      174.68   
71             7.455           8.16         491978      200.68   
240            6.840           8.68         470107      204.80   
6              7.400           8.96         459241      139.16   
417            9.165           6.96         302776      172.16   

     Twitter_hastags  Avg_age_actors  Num_multiplex  3D_available_YES  \
220          224.272              23            536                 0   
71           263.472              46            400                 0   
240          224.320              24            387                 1   
6            243.664              41            522                 1   
417          301.664              60            589                 1   

     Genre_Comedy  Genre_Drama  Genre_Thriller  
220             0            0               1  
71              0            0               0  
240             1            0               0  
6               0            0               1  
417             0            0               0

In [33]:
X_train_STD[:1]

array([[-0.37257438, -0.70492455,  0.42487874,  0.93567804,  0.69366877,
         0.44260898,  0.4259219 ,  0.43335791,  0.44757662,  1.07963602,
         0.44638354,  0.56941731, -0.33434417, -1.31368908, -0.0867923 ,
        -1.10997486, -0.66547513, -0.48525664,  1.3293319 ]])

In [34]:
X_test.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
329            21.3448               61.48               0.540  35179.815   
371           204.6460               91.20               0.369  34529.880   
219            22.2850               82.78               0.450  35402.015   
403           516.0340               91.20               0.307  29713.695   
78             21.1292               80.66               0.563  34618.760   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
329          90.7               7.320                7.460            7.275   
371         173.5               9.310                9.525            9.320   
219         165.9               8.175                8.375            8.315   
403         169.5               9.125                9.310            9.060   
78          127.2               7.330                7.500            7.450   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
329            7.515           8.62         483051  111.040000   
371            9.505           7.96         454281  196.000000   
219            8.405           8.72         451935  123.200000   
403            9.100           6.96         384237  157.391498   
78             7.690           8.26         447528  176.480000   

     Twitter_hastags  Avg_age_actors  Num_multiplex  3D_available_YES  \
329          283.616              53            452                 0   
371          268.000              25            609                 1   
219          263.680              21            561                 1   
403          301.328              40            677                 1   
78           303.392              53            377                 1   

     Genre_Comedy  Genre_Drama  Genre_Thriller  
329             1            0               0  
371             1            0               0  
219             1            0               0  
403             0            0               1  
78              0            1               0

In [35]:
X_test_STD[:,1]

array([-1.12872913,  0.9988844 ,  0.39610829,  0.9988844 ,  0.24434044,
       -0.42716074,  0.9988844 , -0.84953355, -0.17516883, -0.36702631,
        0.9988844 ,  0.9988844 ,  0.9988844 ,  0.9988844 ,  1.21078669,
       -1.27190636,  0.9988844 , -1.37499396, -1.01275558, -0.73928709,
       -0.53597543,  1.21078669, -0.36702631, -0.67485734, -0.60326872,
        0.9988844 , -0.42716074,  1.21078669, -1.17884116, -0.15941933,
        0.9988844 ,  0.9988844 , -0.75360481, -0.88675963, -1.01275558,
        0.9988844 ,  0.9988844 ,  0.9988844 ,  0.9988844 ,  0.9988844 ,
        0.40040361, -0.60326872, -1.12872913,  0.9988844 , -1.32201838,
       -0.58036037,  0.40040361,  1.21078669,  1.21078669, -0.36702631,
        1.21078669, -0.20523604, -0.70492455, -0.75360481,  1.54152608,
       -0.46581859, -0.72496936, -0.96407533,  0.9988844 , -0.07637654,
       -1.35065383, -0.17516883, -0.72067405, -0.70492455,  0.9988844 ,
       -1.10009369,  0.9988844 , -0.46581859,  0.9988844 , -0.07

## Training Regression Support Vector Machine

In [36]:
from sklearn.svm import SVR

In [38]:
svr = SVR(kernel='linear', C = 3000)

In [39]:
svr.fit(X_train_STD, y_train)

SVR(C=3000, kernel='linear')

### Predicting values using trained model

In [42]:
y_test_pred = svr.predict(X_test_STD)
y_test_pred

array([54149.04985486, 42108.34471214, 47533.48916051, 17335.56708281,
       48583.82292107, 39306.44775797, 33505.9535726 , 43171.76493611,
       29476.26499757, 46980.75731107, 12645.08472006, 38648.42247605,
       38048.23936642,  8415.03656142, 67457.69091145, 62224.20392732,
       38975.54675176, 65880.00221637, 56742.36900527, 42713.82149416,
       53525.49453611, 39264.6242224 , 41193.07225572, 58209.33323513,
       42495.88201229, 12132.62441561, 40418.388771  , 29850.91523034,
       75048.6007429 , 43839.06117389, 36786.86517154, 37330.36790834,
       37565.19845685, 40538.47149966, 51853.9891749 , 35081.953653  ,
       25483.31757363, 36025.27585637, 36413.96001026, 36164.40005112,
       47058.89224017, 45705.55298319, 44210.84051282, 27455.32262481,
       50732.91083479, 46541.4643388 , 32853.69351744, 40270.99818314,
       15510.53146758, 52029.40170025, 41465.42768853, 38769.99820302,
       47214.74691352, 68388.92527648, 25170.79907635, 41175.69832861,
      

In [43]:
y_train_pred = svr.predict(X_train_STD)
y_train_pred

array([58878.11306215, 46355.91566302, 56818.87566982, 45800.10218153,
       11984.72611331, 25659.16176502, 45183.6080545 , 56905.3883851 ,
       59740.05421596, 21264.66668753, 36409.75240493, 39535.05622863,
       22696.23370025, 38729.77491254, 20088.71899575, 38254.55607219,
       11671.37591553, 83279.92903305, 55227.39521863, 25194.62646389,
       29375.36178568, 42399.90256858, 47702.64943547, 33634.0997657 ,
       65285.53724074, 31773.8623794 , 36756.61306504, 60249.90039688,
       38727.88676716, 39695.62539614, 28136.0160463 , 41617.5744838 ,
       40914.94472847, 62259.47979006, 50434.22942896, 26720.50786202,
       56043.65383529, 25889.57921884, 31416.11696495, 43862.3546435 ,
       65697.85350402, 55730.8603473 , 48319.42816749, 33200.09160621,
       60152.82262123, 63333.22514056, 36610.9346237 ,  9949.16670882,
       51678.88425947, 48060.55318891, 14748.99872995, 52439.11269918,
       36113.98944882, 55990.45525482, 35540.26302487, 35130.65633238,
      

### Model Performance

In [46]:
from sklearn.metrics import mean_squared_error, r2_score

In [47]:
mean_squared_error(y_test, y_test_pred)

161383675.95784867

In [48]:
r2_score(y_train, y_train_pred)

0.7110100333340962

In [49]:
r2_score(y_test, y_test_pred)

0.49869112364165125